modLoader="javafml"
loaderVersion="[1,)"
license="MIT License"

[[mods]]
modId="suggestion_tweaker"
version="${version}"
displayName="Suggestion Tweaker"
authors="VelizarBG"
description='''
Improves the way suggestions are filtered when writing a command
'''
logoFile = "icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/suggestion-tweaker"
issueTrackerURL = "https://github.com/VelizarBG/suggestion-tweaker/issues"

[[mixins]]
config = "suggestion_tweaker-common.mixins.json"

[[dependencies.suggestion_tweaker]]
modId = "neoforge"
type = "required"
versionRange = "[20.5.0-beta,)"
ordering = "NONE"
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.suggestion_tweaker]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.suggestion_tweaker]]
modId = "cloth_config"
type = "required"
versionRange = "[${cloth_version},)"
ordering = "NONE"
side = "BOTH"
